version: "3"

services:
    mysql:
        image: mariadb
        container_name: db
        restart: always
        volumes:
            - ./database/data:/var/lib/mysql
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        ports:
            - '${DB_PORT}:${DB_PORT}'
#    redis:
#        image: redis:4-alpine
#        container_name: cache
#        restart: always
#        ports:
#            - 16379:6379
#        volumes:
#            - redis:/data
    smtp:
        image: mailhog/mailhog
        container_name: smtp
        logging:
            driver: 'none' # disable saving logs
        ports:
            - '${MAIL_PORT}:${MAIL_PORT}' # smtp server
            - 8025:8025 # web ui

volumes:
    db:
        driver: "local"
#    redis:
#        driver: "local"
